layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
      - kubeletter-clojure
      - dotfiles
      - try-keytty
    # - repo-name

social_media:
  # behance: your_username
  # facebook: your_username
  # dribbble: your_username
  stackoverflow: ryuheechul
  linkedin: ryuheechul
  twitter: ryuheechul
  hashnode: ryuheechul
  devto: ryuheechul
  medium: ryuheechul

topics:
  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kubernetes/kubernetes.png

  - name: Terraform
    web_url: https://www.terraform.io
    image_url: https://www.terraform.io/assets/images/og-image-8b3e4f7d.png
      
  - name: Prometheus
    web_url: https://prometheus.io
    image_url: https://prometheus.io/assets/prometheus_logo_grey.svg

  - name: Vault
    web_url: https://www.vaultproject.io
    image_url: https://s3.amazonaws.com/hashicorp-marketing-web-assets/brand/Vault_VerticalLogo_FullColor.B1xPC0pSax.svg

  - name: DevOps
    web_url: https://github.com/topics/devops
    image_url: https://alln-extcloud-storage.cisco.com/ciscoblogs/5d37d7284e6e8-768x395.png
